[package]
name = "szdt"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "szdt"
path = "src/bin/szdt.rs"

[dependencies]
bs58 = "0.5.1"
ciborium = "0.2.2"
clap = { version = "4.5.31", features = ["derive"] }
data-encoding = "2.8.0"
ed25519-dalek = { version = "2.1.1", features = [
    "alloc",
    "digest",
    "rand_core",
    "serde",
    "signature",
] }
rand = "0.8.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.140"
sha2 = "0.10.8"
