[package]
name = "szdt"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "szdt"
path = "src/bin/szdt.rs"

[dependencies]
bs58 = "0.5.1"
cid = { version = "0.11.1", features = ["serde"] }
clap = { version = "4.5.31", features = ["derive"] }
data-encoding = "2.8.0"
ed25519-dalek = { version = "2.1.1", features = [
    "alloc",
    "digest",
    "rand_core",
    "serde",
    "signature",
] }
multihash = "0.19.3"
rand = "0.8.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_ipld_dagcbor = "=0.6.3"
serde_ipld_dagjson = "0.2.0"
sha2 = "0.10.8"
thiserror = "2.0.12"
unsigned-varint = "0.8.0"

[dev-dependencies]
tempfile = "3.19.1"
